### PR TITLE
Add Runbook

### LINKED ISSUE #940: Runbook
[Runbook](https://github.com/braintree/runbook) is a new automation framework from Braintree. Runbook provides a Ruby DSL and set of tools to build system automation rules and workflows.

It's highly versatile and can be used as a Ruby library within your app or by itself. It supports remote execution via SSHKit, headless/automated mode, Tmux integration, and an extensible DSL.

### PR DESCRIPTION
**Pull request by dcchambers**
## Project

**Runbook**
- https://github.com/braintree/runbook
- https://rubygems.org/gems/runbook

## What is this Ruby project?

Runbook is a framework and Ruby DSL for system automation.

## What are the main difference between this Ruby project and similar ones?

There are many system automation tools, but not many written in Ruby. Runbook is fully-featured and highly extensible.It can work within your application as a library or independently from the command line. It supports remote execution, Tmux integration, headless/automated mode, and more.

Resolves #940 

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by markets** [comment]
oh nice project @dcchambers :ok_hand: maybe still too fresh for this list (~500 downloads), but really promising! Thanks for sharing :+1:

**Comment by dcchambers** [comment]
Checking status of this.

Currently at 441 stars on GitHub and 3500+ downloads on rubygems.

**Comment by markets** [comment]
@dcchambers it's not an "official" rule in Awesome Ruby (yet), but we usually start to take into consideration projects around 10k downloads.

Keep it up, this project seems really interesting 👍

**Comment by markets** [comment]
👀 Similar tool: ActiveWorkflow - An intelligent process and workflow automation platform based on software agents (#948)

**Comment by dcchambers** [comment]
Awesome, thanks @markets!

**Pull request merged**
