### PR TITLE
Add RocketJob

### PR DESCRIPTION
**Pull request by reidmorrison**
Add RocketJob

### CODE REVIEW

**Comment by markets** [comment]
Hi @reidmorrison,

Nice project, a little fresh, but promising!! :+1:

**Comment by reidmorrison** [comment]
RocketJob has been under heavy development by a team of 4 developers. It has been running for almost a year in a large Enterprise mission-critical deployment with over 480 worker threads. It is rock-solid and was built because we out-grew Resque and Sidekiq.

RocketJob is built on top of `Semantic Logger` and `Symmetric Encryption` which are also both well tested in our Enterprise Ruby deployment. The sister project `RocketJob Mission Control` supplies the management web interface for RocketJob. 

We have put in a tremendous amount of effort to make RocketJob ready for OSS distribution, including thorough documentation and full test suites hosted on Travis-CI.

I presented RocketJob at the Tampa Ruby meetup where it was well received.

Please reconsider listing RocketJob since we have invested over $200,000 in RocketJob already, and without exposure we are not able to get others to share in the benefits of our hard work.

The only part missing now is more visibility, which is where `awesome-ruby` can help.

**Comment by markets** [comment]
Hi @reidmorrison,

Awesome Ruby isn't a place to advertise new projects. That said, new projects are also welcome if they fit the [Quality standard](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md#quality-standard): 

* Generally useful to the community.
* Actively maintained (even if that just means take care of open issues).
* Stable.
* Documented.
* Tests.

And are really solid solutions accomplishing new features/approaches, as `RocketJob` does.

Explain some background about the project and how it was built, is a very good way to suggest projects to Awesome Ruby. Thanks and congratulations :+1: :rocket:

**Comment by reidmorrison** [comment]
Thank you :+1:

**Comment by markets** [comment]
@reidmorrison I submitted a post on Reddit Ruby room: https://www.reddit.com/r/ruby/comments/3m76j5/high_volume_priority_based_distributed_background/

**Pull request merged**
