### PR TITLE
add RobustExcelOle

### PR DESCRIPTION
**Pull request by sunito**
added RobustExcelOle as a spreadsheet library.

### CODE REVIEW

**Comment by markets** [comment]
Hi @sunito, thanks for sharing, but we can't consider it a widely-used/top/mature resource in the Ruby community. Seems a bit fresh for now.

**Comment by sunito** [comment]
Hello @markets, I agree, it is not widely used (yet). 
If the "yet" turns out to be valid, will you then automatically reconsider the entry?

**Comment by markets** [comment]
Yes, if the resource meets the quality standard.

**Comment by markets** [comment]
Closing for now, please re-open in case you want to resume that discussion (or the project reaches higher popularity). Thanks!

**Pull request closed without merging**
