### PR TITLE
added credit_card_validations

### PR DESCRIPTION
**Pull request by Fivell**

### CODE REVIEW

**Comment by markets** [comment]
Thanks @Fivell

**Comment by Fivell** [comment]
@markets, same doubts, E-commerce/ORM/Misc

**Comment by markets** [comment]
Under `E-Commerce and Payments` fits semantically better, IMO. I really dislike to add resources into `Misc`...

**Comment by Fivell** [comment]
@markets , done

**Comment by markets** [comment]
Could you please end the description with a `.`(as per contribution guides)?

**Comment by Fivell** [comment]
@markets , sure

**Comment by markets** [comment]
Thanks a lot! :rocket:

**Pull request merged**
