### PR TITLE
Add kimurai

### PR DESCRIPTION
**Pull request by glaucocustodio**
## Project

Kimurai
https://github.com/vifreefly/kimuraframework
https://rubygems.org/gems/kimurai

## What is this Ruby project?

Kimurai is a modern web scraping framework written in Ruby which works out of box with Headless Chromium/Firefox, PhantomJS, or simple HTTP requests and allows to scrape and interact with JavaScript rendered websites.

## What are the main difference between this Ruby project and similar ones?

It supports many engines (headless chromium/firefox, phantomjs etc), highly configurable (headers, delay between requests etc), has built-in helpers (like save_to), has ability to run concurrent requests, handles request errors automatically and more.

Ps: the repo has been archived recently but the gem seems pretty stable.

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by markets** [comment]
Hi @glaucocustodio and thanks for sharing! 

Seems a nice project 👍  but I wouldn't feel comfortable recommending an archived project for new developments. Also, in the past this project was moved from its original location/naming too: https://github.com/markets/awesome-ruby/pull/827#issuecomment-414054594.

**Comment by glaucocustodio** [comment]
Hi, I think this is a mistake as it's a pretty useful framework and we don't have something similar in the list (I've been using it recently even being archived). Adding it to the awesome list would give it more visibility, increasing the odds of someone else picking it up to maintain.

And if it ever gets moved, we can always update the link 🙂

**Comment by markets** [comment]
Hi again @glaucocustodio I understand your points, but Awesome Ruby is not a place to look for new maintainers, promote new projects... imagine if we start handling all those kind of situations, this will become a mess. On the other hand, I don't see in their docs/issues/web a claim for new maintainers, so maybe they just want to shut down the project.

@vifreefly sorry for the ping 🙏  can you please clarify current status/plans?

**Comment by vifreefly** [comment]
@markets  Hello Mark! I was overwhelming with work so I archived the project because I didn't had any time to maintain it. But now I have more time and changed my mind - I plan to release a new 2.0 version of Kimurai in the next month.

**Comment by glaucocustodio** [comment]
Thanks for your great work @vifreefly, I would like to help keeping Kimurai active as well.. Maybe you could create a github organization for the project to be easier to on-board new maintainers?

**Comment by markets** [comment]
Thank you so much @vifreefly for you message! That's really good news, Kimurai seems a really good project in that field.

As @glaucocustodio pointed out, maybe moving to an organization it's a good idea, it will be easier for others to collaborate since eventually a "core" team can be created.

**Pull request merged**
