### PR TITLE
Add Slack Notifier to Messaging

### PR DESCRIPTION
**Pull request by Erol**

### CODE REVIEW

**Comment by markets** [comment]
Hi @Erol, what do you think about `Third-party APIs` section?

**Comment by Erol** [comment]
Yeah, I agree with you on the section and have updated the PR.

**Comment by markets** [comment]
Hi @Erol, thanks for updating it, could you please remove also the title from the TOC?

**Comment by Erol** [comment]
Done!

**Comment by markets** [comment]
:rocket: :shipit:

**Pull request merged**
