### PR TITLE
Add KatakataIrb gem

### PR DESCRIPTION
**Pull request by ybiquitous**
## Project

- https://github.com/tompng/katakata_irb
- https://rubygems.org/gems/katakata_irb

## What is this Ruby project?

KatakataIrb might provide a better autocompletion based on type analysis to irb (an irb plugin).

This gem was [introduced in RubyKaigi 2023](https://rubykaigi.org/2023/presentations/tompng.html).

## What are the main difference between this Ruby project and similar ones?

As far as I know, there are no similar projects.

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by ybiquitous** [comment]
> As per contrib guides, still too fresh for this list (only 1,6k downloads).

Yes, unfortunately, true. 😓 But, I strongly recommend this gem to people who normally use IRB! 
Installation is dead simple, and it should improve your IRB experience!

**Comment by ybiquitous** [comment]
@markets Hello. Finally, KatakataIrb reached out to 2k+ downloads! 🎉 

image

https://rubygems.org/gems/katakata_irb

Could you review it again, please?

**Comment by ybiquitous** [comment]
Oops, I misunderstood "at least 30k downloads" in the contributing guide. 😓 
Sorry for bothering you. I need to wait for a while...

https://github.com/markets/awesome-ruby/blob/5630e7228f81fb5011220dd6ae69dfc8af79ebb0/CONTRIBUTING.md?plain=1#L38

**Comment by markets** [comment]
Yes! no prob @ybiquitous! But this collection can't be a place to promote new projects... this list will become a mess with everyone self-promoting their new gems. We only host projects that reaches certain popularity in the ecosystem.

I'm now working on a different project, where be can list more repos per category (along with some extra info like stars, license, ...) and I just added it there: https://opensource-heroes.com/awesome/ruby/irb

Please spread the word 🙏🏼

**Comment by ybiquitous** [comment]
Thank you for merging!

**Pull request merged**
