### PR TITLE
Added XDG gem.

### PR DESCRIPTION
**Pull request by bkuhlmann**
## Project

See the [XDG](https://github.com/bkuhlmann/xdg) project for details as the project README explains the implementation as well as the XDG Base Directory Specification in more readable terms.

## What is this Ruby project?

Provides an implementation of the XDG Base Directory Specification
which helps CLIs and other programs leverage a common structure for
configuration, cache, and data.

In the past, this gem wasn't well maintained. Prior to Version 3.0.0,
it hadn't been updated in ~7 years. Now, with new ownership, it's got a
new implementation and API which adheres to the XDG Base Directory
Specification.

Further enhancements and examples can be found in the
[Runcom](https://github.com/bkuhlmann/runcom) gem.

## What are the main difference between this Ruby project and similar ones?

There are no comparisons as this gem has been around for many years but provides a fresh update to an implementation which can benefit the greater Ruby community.

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by bkuhlmann** [comment]
Hello, I was checking back in to see if there was any traction on this?

**Comment by markets** [comment]
Hi @bkuhlmann :wave: unfortunately we didn't receive any +1 or comment from the community. Not sure if this resource is a bit "esoteric" (like in #208, #289).

**Comment by bkuhlmann** [comment]
:bow: @markets, yeah, fair point. Would you prefer I close this PR instead? I'm fine with that as it would get my Inbox back to zero. :wink:

**Comment by markets** [comment]
Latest releases have also a small download ratio, so yes, I'd say this is too "obscure" for this list...

Thanks @bkuhlmann

**Pull request closed without merging**
