### PR TITLE
Add Consul Gem

### PR DESCRIPTION
**Pull request by MohamedBasaleh**
## Project

Consul is an authorization solution for Ruby on Rails .

- https://github.com/makandra/consul .
- https://rubygems.org/gems/consul

## What is this Ruby project?

Consul is an authorization solution for Ruby on Rails where you describe sets of accessible things to control what a user can see or edit.

A typical use case in a Rails application is to restrict access to your ActiveRecord models. For example:

- Anonymous visitors may only see public posts

- Users may only see their own notes

- Only admins may edit users

## What are the main difference between this Ruby project and similar ones?

Easy and very fun :heart: :smiling_face_with_three_hearts: 

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by Mohammed-Balfaqih** [comment]
Thanks, Great gem! but you should put the link in alphabetical order as the contribution guide :)

**Comment by MohamedBasaleh** [comment]
sir @markets I have modified the alphabetical order according to the contribution guide

**Comment by markets** [comment]
Hi @MohamedBasaleh, could you please remove the extra `..` stop period?

**Comment by MohamedBasaleh** [comment]
@markets ok :smile:

**Pull request merged**
