### PR TITLE
Fix broken links and replace with correct link

### PR DESCRIPTION
**Pull request by budhrg**
Fix broken links and replace `RDoc` link with updated link.

### CODE REVIEW

**Comment by markets** [comment]
Hi @budhrg, thanks for contributing to Awesome Ruby. Some comments:

- RDoc: 👍 
- Shoppe, more discussion here: #716 => so probably it's a good idea to remove this link right now 👍  (will see in the future if the new fork take off)
- Ruby Hyperloop was moved here => http://ruby-hyperloop.org/, could you please update this?
- Middleman Presentation: @fedux-org @maxmeyer I couldn't found any news, active fork or replacement, do you have more info about what happened to this project?

**Comment by budhrg** [comment]
> Ruby Hyperloop was moved here => http://ruby-hyperloop.org/, could you please update this?

@markets , Done. Thanks

**Comment by maxmeyer** [comment]
@markets Sorry, I totally forgot that I added it to your list. You can safely remove that project. I abandoned it. It was too tightly coupled to an older version of `middleman`. It was too much of effort to support the newer version.

**Comment by markets** [comment]
thanks for the update @maxmeyer, no prob 👍  that was sad :( it was a cool project to build html presentations with Ruby

Do you know any similar tool built with/for Ruby? I'm asking because maybe you moved to other tools that could fit in this list 😺

**Comment by markets** [comment]
@budhrg So that's all ready here, time to merge 🚀 

Thanks! 👍

**Comment by maxmeyer** [comment]
@markets I moved to "pure" `middleman` with some sugar to help me building presentations. I got stuck migrating from "middleman"'s asset pipeline to an external one. I also considering to move to `hugo` (https://gohugo.io/) since I started to use `go` as my main programming language.

**Pull request merged**
