### PR TITLE
add actionview-component

### PR DESCRIPTION
**Pull request by joelhawksley**
## Project

https://github.com/github/actionview-component
https://www.ruby-toolbox.com/projects/actionview-component
https://rubygems.org/gems/actionview-component/

## What is this Ruby project?

ActionView::Component is a framework for building view components in Rails.

ActionView::Components are Ruby classes that are used to render views. They take data as input and return output-safe HTML. Think of them as an evolution of the presenter/decorator/view model pattern, inspired by React Components.

## What are the main difference between this Ruby project and similar ones?

ActionView::Component is similar to other view component libraries, but is specifically designed for tight conceptual integration into Rails. It is an extraction from the GitHub monolith.

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by markets** [comment]
Hi @joelhawksley and thanks a lot for contributing here 👍 

Maybe I'm wrong, but I think View components were merged to Rails, or at least, I remember an open PR with quite similar feature.

**Comment by joelhawksley** [comment]
@markets that PR, https://github.com/rails/rails/pull/36388, only had preliminary support (I'm the author if it 😄), enabling libraries such as ActionView::Component to hook into Rails.

`actionview-component` is the library itself, where we're working on what we plan to upstream into Rails eventually.

**Comment by markets** [comment]
Ah yes! I'm speaking about that pull request 👍 

I'm a bit confused now 🤔... so Rails master has preliminary "support", but not ready to use Components? Or Components can be used, but this library adds more features?

**Comment by joelhawksley** [comment]
Rails master has the hooks necessary to use the `actionview-component` gem, which provides the `ActionView::Component` base class for building view components.

**Comment by markets** [comment]
ok, understood, I just made a quick look at the PR diff 👍 

Nice project! would be amazing to merge this upstream 👌

**Comment by joelhawksley** [comment]
Closing this PR as we are planning to rename the gem.

**Pull request closed without merging**
