### PR TITLE
Add health monitor gem

### PR DESCRIPTION
**Pull request by nirdosh17**
## Project

**Health Monitor Rails**
Github: https://github.com/lbeder/health-monitor-rails
RubyGems: https://rubygems.org/gems/health-monitor-rails

## What is this Ruby project?

A mountable Rails plugin to check health of services(DB, sidekiq, Redis) used by the app.

## What are the main difference between this Ruby project and similar ones?

- Simple and minimalistic
- Easy to add new services according to our need
- Offers different response formats(HTML/JSON/XML) for "/check"  endpoint

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by markets** [comment]
Hi @nirdosh17 cool project! Anyway, I think we don't need a new category, maybe we can add it under [Process Management and Monitoring](https://github.com/markets/awesome-ruby#process-management-and-monitoring). wdyt?

**Comment by nirdosh17** [comment]
@markets I have moved it to `Process Management and Monitoring` category.

**Comment by markets** [comment]
Thanks! could you please add it in alphabetical order, as per contrib guides?

**Comment by nirdosh17** [comment]
> Thanks! could you please add it in alphabetical order, as per contrib guides?

Done!

**Pull request merged**
