### PR TITLE
Added Rails Friendly URLs

### PR DESCRIPTION
**Pull request by calonso**

### CODE REVIEW

**Comment by markets** [comment]
Hi @calonso, I just made a quick read of the Readme doc, it seems lightweight and has pretty good features/design :+1:  

But it also seems a little "fresh", just 440 downloads according RubyGems.

Let's keep this issue open and see how the project evolves.

Thanks for share!

**Comment by calonso** [comment]
Slowly but growing!! 1.212 downloads... Hopefully by merging it into your list I can get some contributors. :)

**Comment by markets** [comment]
Hi @calonso,

Still too fresh IMO, 1k downloads is a low figure. Awesome Ruby isn't a place to promote new projects, imagine if we do the same with all suggestions...

Try to add post on Reddit (Ruby room), HackerNews, RubyFlow, RubyDaily, Twitter... to get more feedback from community and people involved.

Thanks!

**Comment by markets** [comment]
Closing for now, please re-open in case you want to resume that discussion. Thanks!

**Pull request closed without merging**
