### PR TITLE
add ActiveType

### PR DESCRIPTION
**Pull request by stamm**

### CODE REVIEW

**Comment by markets** [comment]
hi @stamm, a while ago we discussed a bit about it... https://github.com/markets/awesome-ruby/issues/196

**Comment by stamm** [comment]
@markets but it present not in list at now. What I need to do: move to that category?

**Comment by markets** [comment]
I'm not sure if we should add this resource, in this case `ActiveAttr` seems, by far, a more popular (stars, downloads, contributors...) and widely used to achieve the same thing.

In addition to inheritance vs mixin, are they significantly different in other ways?

**Comment by stamm** [comment]
It seems, you're right, I'm not go deep to compare this gems

**Comment by markets** [comment]
Closing for now, please re-open in case you want to resume that discussion. Thanks!

**Pull request closed without merging**
