### PR TITLE
Fixing github link redirections

### PR DESCRIPTION
**Pull request by ramirio**

### CODE REVIEW

**Comment by markets** [comment]
wooow thanks a lot @ramirio! :+1: did you run a script or manually?

**Comment by ramirio** [comment]
My initial goal was just change the elastic/logstash link, but I noticed that could be other links with the same situation, so I wrote a little script to handle with the other links too.

**Comment by markets** [comment]
@ramirio I said that because probably would be useful to run the script periodically to detect new redirects (and rules like: repeated links, format, alphabetical order ...). We can even run it remotely on a CI platform, just as other `awesome-*` are doing: 

* https://github.com/h4cc/awesome-elixir/tree/master/tests 
* https://github.com/avelino/awesome-go/blob/master/repo_test.go
* https://github.com/jondot/awesome-react-native
* https://github.com/veelenga/awesome-crystal/blob/master/spec/readme_spec.cr

Would you like to share this script with us? :+1:

**Comment by ramirio** [comment]
:+1: 
```ruby
require 'httpclient'

httpc = HTTPClient.new

file_content = File.open("README.md", "rb").read
links =  file_content.scan(/\(https:\/\/github.com.*?\)/)

for link in links do
   link = link[1..-2]
   resp = httpc.get(link)
   if resp.header['location'][0]
     file_content = file_content.gsub(link, resp.header['location'][0])                                                                                             
   end
end

File.open('README.md', "w") { |file| file.puts file_content }
```
This was basically the script I wrote this morning with a little modification about storing the changes in the file (I used a trick with regexp and vim before).

**Comment by markets** [comment]
Thanks @ramirio :+1:

**Comment by dkhamsing** [comment]
guys, kind of overkill but check out https://github.com/dkhamsing/frankenstein

**Comment by ramirio** [comment]
wow! perfect job @dkhamsing

**Comment by dkhamsing** [comment]
hehe... it's ok https://github.com/pulls?utf8=%E2%9C%93&q=is%3Amerged+is%3Apr+author%3AReadmeCritic

**Comment by markets** [comment]
Hi @dkhamsing, as you already said, kind of overkill for that use-case, but good job :+1: :dart: 

Would be nice a similar project like yours, but more `awesome-*` focused, I mean, with features to parse those kind of collection: redirects, format, order ...

**Pull request merged**
