### PR TITLE
Update Avo description and add to [CMS] category

### PR DESCRIPTION
**Pull request by adrianthedev**
## Project

The project is https://github.com/avo-hq/avo

Site: https://avohq.io/
Repo: https://github.com/avo-hq/avo
Rubygems: https://rubygems.org/gems/avo

## What is this Ruby project?

Avo started out as an admin panel framework but morphed into this advanced content management platform.

I updated the description as it used my original cryptic description that didn't say anything meaningful about the project.

Thank you,
Adrian ✌️

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by markets** [comment]
Hi @adrianthedev 👋🏼 

We list resources under 1 category.

**Comment by adrianthedev** [comment]
Got it! I understand. 
Can I update the description of the project?

**Comment by markets** [comment]
> Can I update the description of the project?

Yes of course! Thank you so much 🚀

**Comment by adrianthedev** [comment]
No, no! Thank you for this project!

**Comment by markets** [comment]
Still didn't tried Avo, but looks really really nice. I'll definitely consider it next time I need and admin or CMS 👌🏼.

We also offer a "sponsors" program in case you're interested. So, your project will be highlighted in this repo and in [the project's website](https://awesome-ruby.com/).

**Comment by adrianthedev** [comment]
Yeah. give it a try next time.
Most people stick with it and are pretty amazed how different it is form the others and how many things you can achieve with it.
I'm here if I can help.

I do help some maintainers with tiny sponsorships. 
Are you talking about the $250/month tier to be featured like BetterStack?
If so, I'm nowhere near that right now 😅, but #lifegoals!

**Pull request merged**
