### PR TITLE
Added Ruby Land News

### LINKED ISSUE #704: http://rubyland.news
Under https://github.com/markets/awesome-ruby#resources

http://rubyland.news

### PR DESCRIPTION
**Pull request by hd719**
Hello I added the website http://rubyland.news under https://github.com/markets/awesome-ruby#resources. 

(https://github.com/markets/awesome-ruby/issues/704)

-Thank you 

(Closes #704)

### CODE REVIEW

**Comment by markets** [comment]
Thanks @hd719, could you please add the link in alphabetical order, as per contribution guidelines?

https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md

**Comment by hd719** [comment]
@markets Will do!

**Comment by hd719** [comment]
@markets I added `Ruby Land` in the list and made sure the list is in alphabetical order.

**Comment by markets** [comment]
Thanks! 🚀

**Pull request merged**
