### PR TITLE
Added EtcUtils

### PR DESCRIPTION
**Pull request by dacamp**

### CODE REVIEW

**Comment by dacamp** [comment]
Anything I can do to get this merged?  If it's me, lmk so I can make changes, otherwise I'll take this as a lesson in patience. :)

**Comment by markets** [comment]
Hi @dacamp,

IMHO we can't cansider it as a "very well-known" resource and widely used by the Ruby community:

* GitHub: 11 stars
* RubyGems: 3,8k downloads

You can find more similar situations reviewing the opened issues and PRs. Sorry sometimes it's hard to draw the line... would be useful if community get more involved commenting (or just +1 -1) on issues, or try to establish a kind of voting system (https://github.com/markets/awesome-ruby/issues/60).

Anyway, I'll try to review all opened suggestions soon.

Thanks.

**Comment by dacamp** [comment]
Completely understand, thanks for the response!

The YaST community had poked around, but never really committed to taking on the high cost of refactoring their stuff away from Perl.  I'll close this out to cut down on your queue.

Thanks!

**Comment by markets** [comment]
Thanks @dacamp for sharing and feedback :+1: 

We just try to mantain a useful collection/resource of MVP (well-known, popular, used, generally useful, active, tested) Ruby tools, that's why I think more comments on suggestions would be really helpful, but it happens few times. 

It probably would be useful for contributors to add some kind of numeric restrictions in [contribution guides - quality standard], something like: stars + forks + followers > 50, downloads > 10k ...

**Pull request closed without merging**
