### PR TITLE
Faalis platform added to admin/dashboard section

### PR DESCRIPTION
**Pull request by lxsameer**

### CODE REVIEW

**Comment by markets** [comment]
hi @lxsameer, nice one! I prefer to add a link in only 1 category, otherwise, it could be chaos :smile:. What category do you think it fits better?

**Comment by lxsameer** [comment]
hi @markets I think Admin section would makes better sense .

**Comment by markets** [comment]
:+1: could you please update the PR?

**Comment by lxsameer** [comment]
@markets can you please merge this ?

**Pull request merged**
