### PR TITLE
Adding Vexor CI

### PR DESCRIPTION
**Pull request by makrusak**
Adding Vexor CI.
https://en.wikipedia.org/wiki/Vexor
https://vexor.io/

### CODE REVIEW

**Comment by makrusak** [comment]
Hello, what does "add link" label mean?

**Comment by markets** [comment]
Hi @makrusak,

It's just means this PR contains a suggestion to add a link to the collection.  

I'm not sure if we should merge this (in reality, we should re-think this "Services" section)... so in these situations I add this label and wait some time comments (or +1, or -1) from community.

**Comment by makrusak** [comment]
@markets.
1. Vexor can run unlimited number of simultaneous builds. When a lot of commits are submitted in a short time developers won’t have to wait in the queue. Also tests in each build are executed simultaneously.
2. You pay for the minutes of testing.
So developers aren’t afraid to make tests parallelized with Vexor because they shouldn't pay for idle servers.
As the result: faster testing, lower price.

**Comment by makrusak** [comment]
So, @markets , what do you think about this pull request?

**Comment by markets** [comment]
Didn't tried yet, but unlimited paralel builds + pay per minutes are really good features! :+1: 

Thanks @makrusak

**Comment by makrusak** [comment]
@markets Maybe do you know any other places to tell about this to community?

**Pull request merged**
