### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by kddeisz**
## Project

prettier

* [github](https://github.com/prettier/plugin-ruby)
* [rubygems](https://rubygems.org/gems/prettier)

## What is this Ruby project?

A automatic code formatter for Ruby.

## What are the main difference between this Ruby project and similar ones?

Similar ones include rubyfmt, rufo, or some aspects of rubocop. The main difference is this uses prettier's main project so it gets the benefits of using their formatter.

### CODE REVIEW

**Comment by markets** [comment]
Cool project @kddeisz 👌 still too fresh for this list (under 5k downloads), but promising.

Thanks for sharing!

**Comment by kddeisz** [comment]
Yeah no worries. Just curious what's the threshold at which you accept it? I didn't see anything in the contributing doc.

**Comment by markets** [comment]
We don't really have set a rule yet, it's hard... sometimes numbers only aren't a good indicator of "awesomeness", but for reference, in my mind I have a number: +10k downloads.

Maybe we should add this info to contribution guides?

In the meantime, we can leave it open, occasionally I review all opened issues and people can comment, +1 ...

**Comment by kddeisz** [comment]
Yeah no worries. The thing with prettier is that it's also a JS package, so most of the downloads have been from that

**Comment by markets** [comment]
> it's also a JS package, so most of the downloads have been from that

:point_up: that's relevant point I think :rocket:

**Pull request merged**
