### PR TITLE
Add Lowkiq

### PR DESCRIPTION
**Pull request by darkleaf**
## Lowkiq

* https://github.com/bia-technologies/lowkiq
* https://bestgems.org/gems/lowkiq
* https://www.reddit.com/r/ruby/comments/dlzz19/ann_lowkiq_ordered_background_jobs_processing/

## What is this Ruby project? && What are the main difference between this Ruby project and similar ones?

In a few words, it is a background task server for special cases, excluding race conditions or deadlocks by design.
There is a comprehensive [Readme](https://github.com/bia-technologies/lowkiq).

It is widely used in companies: 
* https://bia-tech.ru/
* https://www.freshworks.com/

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by solutus** [comment]
:+1:

**Comment by markets** [comment]
hey @darkleaf! this project can potentially be included in this list, but all those current upvotes (+13, this is a record!) seem really fake... Just checking some of the profiles, they are clearly not into the Ruby ecosystem, but other languages/runtimes... 

Thanks for contributing! But please take into consideration that fake upvotes are not gonna help to get this merged.

**Comment by darkleaf** [comment]
I wrote the project several years ago.
Lowkiq has excellent code quality to have minimal effort to support it.

Today it works for big logistic company to process waybills in correct order.
I don't receive bugs from them. It just works.

I'm a programmer not marketer. I don't have skills and time to promote it. 
It was very hard to me to write Readme and write it in English.
It took me several month.
I just want to people have knew about Lowkiq and solved they problems better.

This upvotes are from:
1) my ex colleagues. They use Ruby. They may upvote 6 times.
2) other from my current colleagues. I've just sent a link to this PR to our chat.

**Comment by markets** [comment]
Hello @darkleaf 

> I'm a programmer not marketer. I don't have skills and time to promote it.

Yes, me too, but Awesome Ruby is not a place to promote projects, is a collection of the best/top Ruby resources to build apps. You should post on social media, forums, communities... to let community know about your project. Imagine if people try to promote their projects here... this list will become a mess and will lose all value.

> It was very hard to me to write Readme and write it in English.

Same for me, I'm not native speaker, but this is not a good reason to promote projects here. Hope you understand that point.

---

That said, I think this project can potentially has its place in this collection. The name confused me a bit... as it seems something similar to Sidekiq, but it's more similar to a Kafka  or alike. But +1 from non-Rubysts... doesn't really help to make this project better for the Ruby community. Hope you can understand this point too.

**Comment by solutus** [comment]
We use Lowkiq like Sidekiq queue with ordering as addition to Kafka-like bus. 
Lowkiq allows us to have parallel processing of messages in scope of single order. It cannot be done by our Kafka-like bus. 

We are interested in Lowkiq maintenance by community as one of main tool we used. Though we do not meet any problem with it after 1.0 version for years.

**Pull request merged**
