### PR TITLE
Add Trollop.

### PR DESCRIPTION
**Pull request by guihaojin**

### CODE REVIEW

**Comment by markets** [comment]
Thanks @guihaojin @jdickey, I'm totally agree with @jdickey arguments :+1:

**Comment by kbrock** [comment]
@jdickey I'm sorry you were not able to find a link to a recent version of this gem. [github](https://github.com/manageiq/trollop) [rubygems](https://rubygems.org/gems/trollop)
We've been actively maintaining it for a little while now.

Would you reconsider this position?

**Comment by jdickey** [comment]
@kbrock Yeah; apologies for that. (There really needs to be an emoji for :embarrassed: :P )

Glad to see it got forked and resurrected; looks like you and your team have been putting in a lot of effort. I'd support a PR linking to your GitHub; @guihaojin erred in submitting the PR that he did.

Good luck with the project!

**Comment by guihaojin** [comment]
@kbrock sorry about the out-of-date link and thanks for your information.

I have updated the link and re-submitted the pull request.

**Pull request closed without merging**
