### PR TITLE
Add fasterer referenced in fast-ruby style guide.

### PR DESCRIPTION
**Pull request by juanpastas**

### CODE REVIEW

**Comment by icortex** [comment]
+1

**Comment by markets** [comment]
Hi @juanpastas,
 
I'm also :+1:, but please, as per contrib. guides, submit resources in alphabetical order.

**Comment by juanpastas** [comment]
Thanks. I fixed it.

**Comment by markets** [comment]
:warning: I see an extra * in Flay... Could you please remove it and squash your commits into a single one?

**Comment by juanpastas** [comment]
oh, thanks.

**Comment by markets** [comment]
Squash please and will be ready to merge :rocket:

**Comment by juanpastas** [comment]
Thanks for guiding me. I forced a push, is that ok?

**Comment by markets** [comment]
Thanks @juanpastas now it's ok! :ok_hand:

**Pull request merged**
