### PR TITLE
Add aptly_cli

### PR DESCRIPTION
**Pull request by sepulworld**
[aptly_cli](https://github.com/sepulworld/aptly_cli) - A CLI to interact with Aptly package management servers.

### CODE REVIEW

**Comment by markets** [comment]
Hi @sepulworld, thanks for contributing!

I'm not sure if we should merge these kind of API wrappers to any service... Sorry it's not easy to draw a line here.

I'd say, just keep API wrappers to well-known/popular services: Facebook, Twitter, Salesforce, Trello, Slack...

**Comment by sepulworld** [comment]
Hi @markets makes sense to me.  Thanks for managing this awesome list 👍 

Perhaps this would fit under the Package Management heading?

**Comment by markets** [comment]
You're welcome! 

Or even under `DevOps`, but actually, I think this gem is not really well-known/used by the community (see downloads on RubyGems), at least, right now. In that situations, we'll keep the issue/PR open for some time... probably someone has something to say about... After all, this a community-driven collection.

Thanks.

**Comment by sepulworld** [comment]
Fair enough. I moved it under the DevOps Tools section for now. Thanks for the feedback!

**Pull request closed without merging**
