### PR TITLE
Add Multiwoven

### PR DESCRIPTION
**Pull request by karthik-sivadas**
## Project

Multiwoven - https://github.com/Multiwoven/multiwoven

## What is this Ruby project?

Open-source reverse ETL, data activation platform for data teams developed on RoR 

## What are the main differences between this Ruby project and similar ones?

I haven't seen any other reverse ETL platform build on Ruby on Rails

### CODE REVIEW

**Comment by markets** [comment]
Hello @karthik-sivadas 👋🏼 

Thanks for sharing this resource! Instead of creating such small categories, maybe this should be listed under https://github.com/markets/awesome-ruby#data-processing-and-etl?

**Comment by karthik-sivadas** [comment]
@markets Yeah sure will update accordingly. Thanks for the suggestion.

**Comment by karthik-sivadas** [comment]
Hi @markets, Is there any other change required from my end to get this merged?

**Comment by markets** [comment]
As per contrib guides, resources should be sorted alphabetically.

**Comment by karthik-sivadas** [comment]
> @karthik-sivadas As per [contrib guides](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md#contribution-guidelines), resources should be sorted alphabetically.

@markets Thank you for pointing this out. Sorry, I missed it. I will try to push a fix by tomorrow's EoD.

**Comment by markets** [comment]
Hello @karthik-sivadas 👋🏼 

Any chance to update this PR?

**Comment by markets** [comment]
@karthik-sivadas friendly ping! Any update regarding my last message?

**Comment by Mohith93** [comment]
@markets This will continue to be an open-source project. 

Would you please guide me with the next steps?

**Comment by markets** [comment]
Basically this: https://github.com/markets/awesome-ruby/pull/1130#issuecomment-2003279505

**Comment by markets** [comment]
Hey @Mohith93 👋 any chance to move this forward?

**Pull request closed without merging**
