### PR TITLE
Update clockwork

### PR DESCRIPTION
**Pull request by knoxknox**
Update link and description for gem 'clockwork'.
Looks like this gem is not maintained by original authors.

### CODE REVIEW

**Comment by markets** [comment]
hi @knoxknox, but the original source points out:

> This fork is no longer maintained, maybe try this one: https://github.com/Rykian/clockwork

But I also found this: https://github.com/Rykian/clockwork/issues/1.

So I'm not sure if this is really an option right now...

**Comment by knoxknox** [comment]
Hi @markets, yes I saw this, but this is one of the authors of this gem.

What is your suggestion ?
Also I'm not sure about rubygems. Looks like version in rubygems also is not maintained.

**Comment by markets** [comment]
Yes, there is actually some uncertainty... I also found this thread on Reddit: https://m.reddit.com/r/rails/comments/5a68on/what_happened_to_the_clockwork_gem 

So, probably right now best movement is to remove it from the list (we can add it back in case the project "revives" again). Btw, zhong seems a good lib for a distributed solution: https://github.com/nickelser/zhong

**Comment by knoxknox** [comment]
@markets done, gem was removed from list

**Comment by markets** [comment]
Thanks @knoxknox, this is a proper move IMHO!

There is also a discussion here, in the original repo: https://github.com/adamwiggins/clockwork/issues/23

**Pull request merged**
