### PR TITLE
Added DuckRails (https://github.com/iridakos/duckrails)

### PR DESCRIPTION
**Pull request by iridakos**

### CODE REVIEW

**Comment by markets** [comment]
Hi @iridakos thanks for sharing this! Amazing tool 👍 

I'm not sure about the section, `DevOps Tools`?

**Comment by iridakos** [comment]
Hi @markets,

Thank you!
I'm not sure either. Feel free to move it to whichever section you think it fits better (or reply to this and I'll move it). :D

**Comment by markets** [comment]
Probably under `Testing` fits better 😄. Thanks!

**Comment by iridakos** [comment]
@markets Done :)

**Comment by markets** [comment]
Thank you 👍 🚀 

Nice tool, keep it up!

**Comment by iridakos** [comment]
@markets I will, thank you very much for the addition 👍

**Pull request merged**
