### PR TITLE
Added PluggableJs to Misc category

### PR DESCRIPTION
**Pull request by peresleguine**

### CODE REVIEW

**Comment by markets** [comment]
Hi @peresleguine, nice one. What are the advantages regarding `Gon`?

**Comment by peresleguine** [comment]
Hey @markets. Well, the main purpose is to run page-specific javascript. Passing data is additional functionality. Could be helpful to someone who is searching lightweight solution covering these two issues.

**Comment by markets** [comment]
Thats's right :+1:

**Comment by peresleguine** [comment]
Awesome, thanks!

**Pull request merged**
