### PR TITLE
Add Derailed Benchmark

### PR DESCRIPTION
**Pull request by fpgentil**
Derailed benchmark is some sort of collection of other gems to perform a benchmark. I wasn't sure if it should fit here as it's focused on Rails, but you can also use with Rack so I gave it a shot :smile: 

```
url: https://github.com/schneems/derailed_benchmarks
description: Go faster, off the Rails - Benchmarks for your whole Rails app
```

### CODE REVIEW

**Comment by markets** [comment]
So, what do you think if we modify a bit the description to be clear about Rack compatibility?

**Comment by fpgentil** [comment]
It makes sense, I'll update the PR..

**Comment by fpgentil** [comment]
What do you think, @markets? :smile:

**Comment by markets** [comment]
Thanks! Now it's more precise :+1:

**Pull request merged**
