### PR TITLE
Add lol_dba to database tools

### PR DESCRIPTION
**Pull request by vicmaster**
lol_dba is a small package of rake tasks that scan your application models and displays a list of columns that probably should be indexed. Also, it can generate .sql migration scripts. http://plentz.github.com/lol_dba/

### CODE REVIEW

**Comment by markets** [comment]
Hi @vicmaster, I want to merge this gem, could you please add the resource in alphabetical order (as per contrib guides)? Thanks :+1:

**Comment by vicmaster** [comment]
Sure!, I'll do those changes, thanks in advance! :+1:

**Comment by vicmaster** [comment]
Done! :shipit:

**Comment by markets** [comment]
Thank @vicmaster! :rocket:

**Pull request merged**
