### PR TITLE
Add "JSONAPI::Utils" into "API Builder" section.

### PR DESCRIPTION
**Pull request by tiagopog**
[JSONAPI::Utils](https://github.com/tiagopog/jsonapi-utils) is probably one of easiest yet powerful ways for building [JSON API](http://jsonapi.org)-compliant APIs on Rails. It's all about defining a resource class and using the `jsonapi_render` on your controller actions.

### CODE REVIEW

**Comment by markets** [comment]
Nice one @tiagopog! On the radar :eye:

**Comment by tiagopog** [comment]
Nice, thanks :-)

**Comment by tiagopog** [comment]
Hey there!

Can this PR be merged? The gem has almost 22k downloads and it meets the [Contribution Guidelines](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md).

Thanks.

**Comment by markets** [comment]
Thanks @tiagopog 🚀

**Pull request merged**
