### PR TITLE
Github Changelog Generator

### PR DESCRIPTION
**Pull request by skywinder**
Add one more awesome project :boom:

### CODE REVIEW

**Comment by markets** [comment]
Hi @skywinder, nice lib :gem: :+1: 

I've seen it in `Trending` during last week, congrats! 

I want to merge this, but not sure about category... what do you think about [Documentation](https://github.com/markets/awesome-ruby#documentation)?

**Comment by skywinder** [comment]
@markets thanks! :smile:  

I agree, the functionality is closer to Documentation, than to abstract "Services and Apps" section. So, let's change it to Documentation. I will update PR right now.

**Comment by skywinder** [comment]
Done!

**Comment by markets** [comment]
Thanks @skywinder :rocket:

**Pull request merged**
