### PR TITLE
Add rack-time-zone-middleware into list

### PR DESCRIPTION
**Pull request by merqlove**

### CODE REVIEW

**Comment by markets** [comment]
hi @merqlove, thanks for sharing! Actually, a bit fresh for this list!

**Comment by merqlove** [comment]
@markets yeah, but first star achieved :) i did it because found this pattern really helpful for application performance. we can close this PR currently, i will reopen it on some progress.

**Comment by markets** [comment]
> we can close this PR currently, i will reopen it on some progress.

100% agree

So, for example, in a Rails application, is this approach significantly performant rather than a controller around_action callback?

**Comment by merqlove** [comment]
@markets, anyone able to write same logic in the controllers (via plain methods, concerns, services, ...), but because of cookies parsing, i found that really helpful to split this code into a middleware, because it is unrelated to the business logic. As we do it with Warden or Devise.

**Pull request closed without merging**
