### PR TITLE
Add Heroku CLI

### PR DESCRIPTION
**Pull request by Erol**

### CODE REVIEW

**Comment by Erol** [comment]
Hi @markets, just revisiting this. What are your thoughts on having this merged?

**Comment by Erol** [comment]
Hmmm that's weird, something might have went wrong with the rebase. If you're good with this addition, I can create a new PR instead. :)

**Comment by markets** [comment]
Hi again @Erol, to be honest, not sure 😅 . Although Heroku (and by extension the CLI) it's pretty relevant, I think they are rebuilding the next version in Go: https://github.com/heroku/cli#overview

**Comment by Erol** [comment]
Got it. Thanks for the feedback!

My recent sync to upstream did a merge instead of a fast-forward, and I'm planning to refork the repo. I'm going to close this for now, as well as all of my other PRs which will be affected when I refork. 😅

**Pull request closed without merging**
