### PR TITLE
Add HexaPDF to the PDF section

### PR DESCRIPTION
**Pull request by ramirio**

### CODE REVIEW

**Comment by markets** [comment]
Thanks! Similar to #650

**Comment by markets** [comment]
By the way, HexaPDF seem a very solid and well designed project:
- http://gettalong.org/blog/2016/pdf-object-representation-in-hexapdf.html
- http://gettalong.org/blog/2016/hexapdf-performance-benchmark.html

**Comment by markets** [comment]
I just installed and tried this lib... Amazing job @gettalong 👍 

Although the project is quite new and isn't so much popular yet... It's definitely awesome Ruby

**Comment by gettalong** [comment]
@markets Thanks! :smile:

**Pull request merged**
