### PR TITLE
Rails app generator

### PR DESCRIPTION
**Pull request by khusnetdinov**
Added one more rails generator

### CODE REVIEW

**Comment by markets** [comment]
Thanks for sharing this @khusnetdinov!

A bit fresh for now, only 1k downloads according RubyGems. 

What are the pros against the other projects in that category? 

Similar situation to #530

**Comment by khusnetdinov** [comment]
Each project has the same features with other. Gem differs from other by possibility create app using default flags, for example --api for creation little bit another application scaffold, manage predefined composition of Gemfile by using additional options (3 in TODO, and possible to add more). It also allow you to build on top Docker container with "12 factors rules" - passing and checking ENV variables. I think it's a more flexible and allow you to use Docker in "right way".

**Comment by markets** [comment]
Thanks for your answer @khusnetdinov! Let's wait some time to see if the project reaches some popularity and adoption.

**Comment by khusnetdinov** [comment]
Ok! Please don't close MR.

**Pull request closed without merging**
