### PR TITLE
Add choonkeat/attache to File Upload

### PR DESCRIPTION
**Pull request by JuanitoFatas**
https://github.com/choonkeat/attache

Preview: https://github.com/JuanitoFatas/awesome-ruby-1/blob/add-choonkeat-attache-to-file-uploading/README.md#file-upload

### CODE REVIEW

**Comment by markets** [comment]
Hey @JuanitoFatas, thanks for sharing this resource! :smiley: 

What are the pros/cons compared to the other gems? Is it production ready? Or do you know people/teams using it? According to RubyGems, it has been downloaded 4k times, not so much...

**Comment by JuanitoFatas** [comment]
> What are the pros/cons compared to the other gems?

Better see the [slides](http://www.slideshare.net/choonkeat/file-upload-2015) and [blog post](http://blog.choonkeat.com/weblog/2015/10/file-uploads-2015.html) so I won't repeat here. :blush: 

> Is it production ready? Or do you know people/teams using it?

Yes. I know few teams already use on production. :wink: 

> According to RubyGems, it has been downloaded 4k times, not so much...

I do not think download counts prove anything :sweat:

**Comment by markets** [comment]
Hi @JuanitoFatas! funny slides by the way :bowtie: 

Downloads aren't the unique source of truth, agreed, but are telling you how much projects/people are using the project. So, at the end, it's not a so bad property to review when defining the quality-standard (aka "awesomeness"). 

That said, I'm +1 on this one, I like the different approach to solve the problem. One thing I'll ask, could you please add a more accurate description :blush:? 

Thanks!

**Comment by markets** [comment]
@choonkeat good work! and funny slides by the way :bowtie:

**Comment by choonkeat** [comment]
> could you please add a more accurate description 

Standalone image and file server to decouple your app from file management concerns :bow:

**Comment by JuanitoFatas** [comment]
Thanks!

**Comment by markets** [comment]
you're welcome @JuanitoFatas, gracias a ti!

**Pull request merged**
