### PR TITLE
Add Cloudsmith (a Rubygems-compatible service)

### PR DESCRIPTION
**Pull request by lskillen**
## Project

[Cloudsmith](https://cloudsmith.io) - https://cloudsmith.io

## What is this Ruby project?

This PR adds a link to [Cloudsmith](https://cloudsmith.io), which is a package management service SaaS. It's commercial, but it is completely free for open-source and it has generous free tiers otherwise. It has first-class support for Rubygems-compatible repositories (and many other package formats, such as Python/Npm), plus org/teams management, granular access controls, private repositories, repository-specific entitlements, a worldwide content distribution network, webhooks, access logs, etc.

## What are the main difference between this Ruby project and similar ones?

It's similar to [Gemfury](https://gemfury.com), which is another excellent service for managed hosting of Rubygems. Cloudsmith has a focus on simplicity and an ethos for being as secure as possible by default, which is seen in the breadth of features offered (e.g. automatic GPG signing, entitlements control, geo/IP control, etc.) It's particularly useful if combining Ruby-based technologies with others (e.g. Npm).

*Full disclosure:* I work at Cloudsmith.

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by lskillen** [comment]
@markets Any comments for consideration? :)

**Comment by markets** [comment]
Hi @lskillen never used that kind of service, neither Gemfury (not listed here btw), I just use Bundler with `:git` option (with `:tag` and `:ref` for versioning/freezing) for private gems. So, I'm not sure how useful/essential is this for Ruby teams. I'd like to hear more opinions from other Ruby developers before merging this. I'm not saying your service isn't useful at all, but I'm not a consumer of those 3rd party services for gems management.

**Comment by lskillen** [comment]
Not a problem, happy to discuss it!

Other competitors to look up who have support:

- JFrog Artifactory
- Sonatype Nexus
- Packagecloud

Snippet from Ruby gems official docs:

https://guides.rubygems.org/run-your-own-gem-server/
> There are times you would like to run your own gem server. You may want to share gems with colleagues when you are both without internet connectivity. You may have private code, internal to your organization, that you’d like to distribute and manage as gems without making the source publicly available.

Other reasons we see people use private servers:

- Ops want to deploy from gem server and not from github (or similar). Either due to security/control (don't want to provide direct access to code) or for simplicity (deploying a gem can be easier), or for resilience (remove reliance on Github, or to provide additional redundancy, or they want to mirror public packages to control them).

- Vendors prefer distributing licensed code via something like Cloudsmith rather than git. Similar to reasons for Ops above, except it is much easier to automate licensing, access to packages, distribution to customers, logging/tracking on use of packages, etc.

- Finally, it starts to make more sense when you are coming Ruby with other technologies, and you want a single unified place to manage assets. This becomes important when scaling beyond single developers into multiple teams.

These are from real world use. :)

**Comment by markets** [comment]
Pretty good reasons! :rocket:

**Comment by lskillen** [comment]
Appreciated @markets, thank you for consideration!

**Pull request merged**
