### PR TITLE
Add IFTTT/polo

### PR DESCRIPTION
**Pull request by nettofarah**
Polo lets you create snapshots of production data so you can work with real world data in development.

### CODE REVIEW

**Comment by markets** [comment]
Hi @nettofarah, thanks for that :+1: 

For now, it seems a bit fresh, just 900 downloads according to RubyGems...

**Comment by nettofarah** [comment]
Hey, Marc!
It is recent indeed. I believe being backed up by IFTTT would be a sign of
good quality though.

We use Polo basically every day and would love to see it grow even more in
the community :)

**Comment by markets** [comment]
Of course! Looks promising, that's why we keep the PR opened some time, I review pending PRs every so often... To get more people involved and community feedback/usage I recommend you to post on: RubyFlow, RubyWeekly, RubyDaily, Reddit (Ruby room)...

You're doing a very good job with OSS! :+1:

**Comment by nettofarah** [comment]
Sounds good! Thanks a lot @markets

**Comment by nettofarah** [comment]
Hi, @markets.
We got some really good traction these last couple of weeks (3x stars) on github.
People are actively submitting PRs and opening new issues.

**Comment by markets** [comment]
Yes, it got some attraction, but RubyGems downloads, that is to say, people using it, is quite low yet... 300 downloads. Let's wait a little longer.

**Comment by nettofarah** [comment]
Sure! No problem!

**Comment by nettofarah** [comment]
hey, @markets.
Maybe now is a good time?

**Comment by markets** [comment]
@nettofarah 🚀 👍

**Comment by nettofarah** [comment]
thanks, @markets!

**Pull request closed without merging**
