### PR TITLE
Add noticed gem

### PR DESCRIPTION
**Pull request by marcoroth**
ActionMailer-like Notification System for your Ruby on Rails app.

## Project

* [GitHub Repo](https://github.com/excid3/noticed)
* [RubyGems](https://rubygems.org/gems/noticed)
* [GoRails Episode](https://www.youtube.com/watch?v=Scffi4otlFc)

## What is this Ruby project?

Noticed is a gem for adding notifications to Rails apps. Notifications are really complicated to build and @excid3 has done the heavy lifting for us. The notifications are delivered in so-called delivery methods and noticed currently supports six different delivery methods out of the box.

## What are the main difference between this Ruby project and similar ones?

Noticed is very Rails-like and abstracts the complex topic into an easy to use gem. 
If you are familiar with the ActionMailer framework you got the basic idea. 

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by excid3** [comment]
🥰

**Comment by markets** [comment]
🚀  nice one! however, not sure about the category 🤔

**Comment by marcoroth** [comment]
I agree! I also thought about that, "E-Mail" was the best fitting one. 

Would it make sense to add a "Notifications" section and pull in some gems from the "Mobile Development" section since they are also related to notifications?

**Comment by markets** [comment]
100% agree 👌  would you like to do it in this PR?

**Comment by marcoroth** [comment]
@markets does that fit? Would you move any other gem in this new section?

**Comment by markets** [comment]
yes 👍  thank you so much!

**Pull request merged**
