### PR TITLE
added profieIT link

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by markets** [comment]
Hi @ferdinandrosario, thanks for sharing!

What do you think to move it under [services and apps](https://github.com/markets/awesome-ruby#services-and-apps)? Actually, `Performance Monitoring` section contains the agents (ruby plugins) to those services.

**Comment by ferdinandrosario** [comment]
That sound good @markets I will modify it.

**Comment by markets** [comment]
Thanks!! :rocket:

**Comment by ferdinandrosario** [comment]
:thumbsup:

**Pull request merged**
