### PR TITLE
add MaglevCMS

### PR DESCRIPTION
**Pull request by did**
## Project

- Website: https://www.maglev.dev
- GitHub: https://github.com/maglevhq/maglev-core
- RubyGems: https://rubygems.org/gems/maglevcms

## What is this Ruby project?

MaglevCMS is an open source page builder embeddable in any Rails 6+ application. It comes with a sleek UI, live editing and generators to create custom editable sections or blocks. 
A PRO version but not open source is also available for SaaS Rails applications which requires to support hundreds of landing pages or microsites.

## What are the main difference between this Ruby project and similar ones?

This is probably the first page builder similar to Elementor available in Ruby on Rails. 

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by markets** [comment]
hello @did 👋🏼 still a bit fresh (only 4k downloads, but [30k required](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md#quality-standard)) for this list, but very promising 👌🏼 

Added here: https://opensource-heroes.com/awesome/ruby/cms

**Comment by did** [comment]
Hey @markets, thanks for the reply! My bad, I didn't catch the `30k required` rule. I'll poke you once I reach this number.

Regarding the second link, if I change the title in my gem spec, will it update the summary in your site?

**Comment by markets** [comment]
> Regarding the second link, if I change the title in my gem spec, will it update the summary in your site?

Not really, we're currently fetching all data via GH API.

**Comment by did** [comment]
thanks a lot @markets!

**Pull request merged**
