### PR TITLE
AuditRails an audit-trail and analytics tool

### PR DESCRIPTION
**Pull request by gouravtiwari**
I extracted this gem out of an app and enhanced Analytics part. Please check if it is a fit for analytics section.

### CODE REVIEW

**Comment by markets** [comment]
Hi @gouravtiwari, looks promising :+1: Let's keep this issue open to see how it evolves. Thanks!

**Comment by gouravtiwari** [comment]
Thanks @markets sorry missed out on alphabetize, corrected the order now,

**Comment by markets** [comment]
@gouravtiwari ok! Good luck with Audit Rails :construction:

**Comment by markets** [comment]
Closing for now, please re-open in case you want to resume that discussion. Thanks!

**Pull request closed without merging**
