### PR TITLE
Add Docsplit

### PR DESCRIPTION
**Pull request by sadfuzzy**
Docsplit - convert ppt and other documents into processable parts

### CODE REVIEW

**Comment by markets** [comment]
Hi @sadfuzzy, nice project! Anyway, not sure about category... what do you think about https://github.com/markets/awesome-ruby#spreadsheets-and-documents?

**Comment by sadfuzzy** [comment]
@markets, good idea

**Comment by markets** [comment]
:+1: Feel free to update this PR when you have a chance. Please, don't forget to squash your commits.

**Comment by sadfuzzy** [comment]
@markets, done!

**Comment by markets** [comment]
Thanks! :shipit: :rocket:

**Pull request merged**
