### PR TITLE
Add overmind to list of Procfile managers.

### PR DESCRIPTION
**Pull request by csalvato**
## Project

Overmind – https://github.com/DarthSim/overmind

## What is this Ruby project?

Overmind is a Procfile runner that runs on tmux

## What are the main difference between this Ruby project and similar ones?

Compared to it's competitor, foreman, Overmind enables running Procfiles on tmux. This gives it the ability to more easily start, stop, restart and kill individual processes, as well as connecting to each process for the ability to debug using something like `pry`.

I personally moved over from foreman to Overmind in the past year, and have loved it so far. Can't find a fault - only improvements on top of foreman.

---

Please help us to maintain this collection by using reactions (:+1:, :-1:) and comments to express your feelings.

### CODE REVIEW

**Comment by onerinas** [comment]
@csalvato thanks for the addition. I moved to overmind recently and its a great experience!

**Comment by markets** [comment]
@csalvato Overmind seems a very solid (and probably powerful) solution, but why we should add it here? It's not Ruby specific, neither is written in Ruby... if we start adding any kind of project to this list, it will become harder to maintain it and a bit confusing IMHO.

**Comment by csalvato** [comment]
@markets I may be unclear on the purpose of this repo.

My understanding was that it was a resource of packages that will help developers using Ruby (despite it being Ruby specific or implemented in Ruby).

From that lens, as a Rails developer, over mind has literally changed my life.

But if that’s not the purpose of this repo, and it’s only about adding Ruby specific and written-in-Ruby projects, it’s not a fit

**Comment by markets** [comment]
Hi @csalvato, 

Sorry, sometimes is hard to draw the line... Awesome Ruby is a collection of TOP/MVP Ruby gems/libs/apps to help the community using Ruby. 

Ideally all resources should be Ruby specific in some way, otherwise this collection can grow exponentially with any kind of: tool, service, plugin, frontend library, devops stuff... but of course, if a non-specific Ruby project literally "change life" of Ruby developers, we can consider its addition 👌🏼  to the collection. As stated in the contribution guidelines: 

> These are just guidelines, not rules, use your best judgment and feel free to propose changes to this project

Best,
Marc

**Comment by csalvato** [comment]
Looks like this won't get merged. Closing it out :(

**Comment by marcoroth** [comment]
+1 for Overmind. It's my default nowadays

**Comment by markets** [comment]
Maybe we can reconsider this addition 🤔? Even I still have some doubts (mainly due to the fact that is non-Ruby specific, see https://github.com/markets/awesome-ruby/pull/1024#issuecomment-778415498), if you read the docs and articles on the internet... looks like it's kind of Rails related tool.

**Pull request closed without merging**
