### PR TITLE
Add Open Source Rails project

### PR DESCRIPTION
**Pull request by mbajur**

### CODE REVIEW

**Comment by markets** [comment]
Hi @mbajur, we discussed a bit about Open Source Rails here: https://github.com/markets/awesome-ruby/pull/154. At the time, it was little unmaintained. What's the current status?

**Comment by mbajur** [comment]
Oh right, it's true, it was unmaintained. However, me and two other folks
decided to start it again and we've been adding one app per week for the
last 3 months :)

**Comment by markets** [comment]
In that case, yes, it's a valuable resource. Could you please re-sort in alphabetical order (as per contribution guides)?

**Comment by mbajur** [comment]
Done. Sorry, completely forgot about that.

**Comment by markets** [comment]
Thanks! :rocket:

**Pull request merged**
