### PR TITLE
Add proxy_pac_rb to testing

### PR DESCRIPTION
**Pull request by maxmeyer**

### CODE REVIEW

**Comment by markets** [comment]
Thanks for sharing @maxmeyer. This gem looks nice, but I think we can't consider it as a well-known resource. We should add only well-known and popular used tools to keep some value on this list.

**Comment by maxmeyer** [comment]
> This gem looks nice, 

Thanks a lot. :smile:

> well-known resource. We should add only well-known and popular used tools to keep some value on this list.

Mmh... I thought the list is kind of a source for finding "diamonds" - I avoid the word gem here to prevent misunderstandings - something like I have problem x and want to find a gem which solves my problem.

No offense, but what's the worth of having five different gems for commandline parsing?

Maybe it does make sense to add this `We should add only well-known and popular used tools to keep some value on this list.` to the CONTRIBUTIONS.md then?

**Comment by maxmeyer** [comment]
Or maybe it does make sense to add something like... you need a least "20" stars to be interesting for the list.

**Comment by markets** [comment]
Hi @maxmeyer, first of all thanks for your feedback, much appreciated :+1: 

We also discussed this topic here: https://github.com/markets/awesome-ruby/issues/304#issuecomment-72120807.

It seems would be a good idea to add this quantitative measures to the contrib guides, ie: stars+contributors > 50, active last year and >10k downloads.

Sometimes it's not easy to draw the line... but if we add all resources nor will help :shipit:

A kind of voting system (via GH issues https://github.com/markets/awesome-ruby/issues/60) probably could help to maintain the collection.

**Comment by markets** [comment]
Closing for now, please re-open in case you want to resume that discussion. Thanks!

**Pull request closed without merging**
