### PR TITLE
Added ActsAsRecursiveTree

### PR DESCRIPTION
**Pull request by SyedMSawaid**
## Project
**Title:** ActsAsRecursiveTree
[Github Link](https://github.com/1and1/acts_as_recursive_tree)
[RubyGems](https://rubygems.org/gems/acts_as_recursive_tree)

## What is this Ruby project?
It makes ActiveRecord as a recursive tree where children can have children and so on. It provides a ton of methods to traverse the tree or load the whole tree at once and then traverse it.

## What are the main difference between this Ruby project and similar ones?
It is almost like `acts_as_tree` but provides a ton of methods for loading the whole ancestory of a node and so on.

### CODE REVIEW

**Comment by markets** [comment]
Hey @SyedMSawaid 👋🏼 

Please, you should add some relevant description, as the proposed template: the https://github.com/markets/awesome-ruby/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by SyedMSawaid** [comment]
@markets the PR's description?

**Comment by markets** [comment]
Yes! That's why we created a pull request template.

**Comment by SyedMSawaid** [comment]
@markets Alright. I added the description. If there is anything else, let me know.

**Pull request merged**
